### ISSUE TITLE
Surface better exceptions

### ISSUE THREAD

**Issue by geowurster** [geowurster/tinymr#22]
Running inside of a multiprocessing job makes identifying issues difficult.  All I can derive from this is that there is an issue in the reducer, but I have no idea what it is.  I have identified a generator that is likely the culprit but cannot access to real underlying error:

```console
DEBUG:tinymr-C:Running map
DEBUG:tinymr-C:Finished map with 10 keys
DEBUG:tinymr-C:Initializing reduce phase
DEBUG:tinymr-C:Running reduce
0
Traceback (most recent call last):
  File "c.py", line 106, in <module>
    results = c(reader('stuff.json', 10), log_level=logging.DEBUG)
  File "/Users/kwurster/code/benthos-pipeline/venv/lib/python2.7/site-packages/tinymr/memory.py", line 170, in __call__
    for key, values in chain(*(iteritems(r) for r in run)):
TypeError: type object argument after * must be a sequence, not generator
```

**Comment by geowurster** [comment]
Found it.  I was passing a string to `ujson.load()` instead of `ujson.loads()`, so this is the exception I should have encountered:

```
>>> import ujson
>>> f = open('LICENSE.txt')
>>> ujson.load(next(f))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-bd6f889453f7> in <module>()
----> 1 ujson.load(next(f))

TypeError: expected file
```

**Comment by geowurster** [comment]
Done enough in https://github.com/geowurster/tinymr/pull/24.
